import { Leaf, Sun, ShieldCheck } from "lucide-react";
import type { ProductData } from "./ProductDetail";

const BASE = "https://www.theroofstore.net";

export const fungalShield: ProductData = {
  slug: "fungalshield",
  name: "Fungal Shield",
  tagline: "Save Your Tiles — Florida's Clear Anti-Fungal Roof Tile Sealer & Anti-Algae Coating",
  category: "RP1 — Anti-Fungal Roof Coating & Clear Roof Tile Sealer",
  icon: Leaf,
  accentColor: "text-green-700",
  badgeColor: "bg-green-100 text-green-700",
  seoTitle: "Fungal Shield (RP1) — Roof Tile Sealer | The Roof Store FL",
  seoDescription: "Fungal Shield (RP1) is a clear roof tile sealer that eliminates black streaking, algae, mold, and fungal growth on Florida tile, metal, and flat roofs. Also works as a protective clear metal roof coating. A stronger alternative to standard roof painting for tile and metal roofs. Mildew resistant. 5-Year Product Warranty. $190 — Free quote 954-210-9614.",
  heroDesc: "Sheds water, prevents staining, eliminates black streaking — and keeps tiles looking new.",
  heroImage: `${BASE}/images/homeshow-small.JPG`,
  heroImageAlt: "Fungal Shield RP1 clear anti-fungal roof coating applied to Florida tile roof — eliminates black streaking and algae",
  overview: [
    "Fungal Shield (RP1) is RoofProtect's clear anti-fungal roof coating, available exclusively through The Roof Store — the answer to South Florida's most common roof complaint: black streaks, green algae patches, and mold colonies that make a perfectly sound roof look like it needs replacing. These aren't cosmetic issues — they are living biological organisms actively breaking down your roofing substrate.",
    "Fungal Shield starts from a clear elastomeric base, to which additional active ingredients are added to create its biocide formula. It penetrates and bonds to clay tile, concrete tile, metal, and flat roof surfaces, killing existing biological growth while creating a long-lasting barrier against future infestations. It sheds water away from the tile surface, prevents staining, and provides UV protection — all in a clear finish that preserves the original look of your roof.",
    'Manufactured by RoofProtect at their Davie, Florida facility as a true liquid rubber coating — 100% without water, fillers, thickeners, or extenders. Every batch is the same proprietary formula refined over 30 years. The 5-Year Product Warranty is included standard. As our own slogan says: "Save Your Tiles."',
    "Many homeowners search for a \"roof painting\" solution when they notice black streaks or algae — Fungal Shield is that idea taken to a professional level: a biocide-active clear formula engineered specifically to kill and prevent biological growth, not just cover it up.",
  ],
  features: [
    { title: "Active Biocide Formula", desc: "Kills algae, mold, and fungus at the cellular level — eliminates black streaking caused by Gloeocapsa magma bacteria." },
    { title: "Prevents Re-Infestation", desc: "Creates a permanent biological barrier that inhibits future mold, mildew, algae, and fungal growth." },
    { title: "Sheds Water & Prevents Staining", desc: "Waterproofs the tile surface and prevents biological staining from taking hold after application." },
    { title: "UV Protection", desc: "UV-stable formula protects tile surfaces from sun degradation under Florida's intense solar exposure." },
    { title: "Mildew Resistant — Guaranteed", desc: "Less cleaning required. Guaranteed mildew resistance is written into the product warranty." },
    { title: "Clear Finish", desc: "Preserves the original appearance of your tiles — no color change, no visible coating, just a protected roof." },
    { title: "Doubles as a Clear Metal Roof Coating", desc: "Bonds to metal roof panels the same way it bonds to tile — a clear, protective metal roof coating that stops rust-driven staining and biological growth without changing the panel's finish." },
  ],
  specs: [
    { label: "Product Code", value: "RP1 — Fungal Shield" },
    { label: "Formula", value: "Clear liquid rubber acrylic — no water, fillers, or extenders" },
    { label: "Coverage Rate", value: "~90 sq ft per gallon" },
    { label: "Finish", value: "Clear — no color change to tiles" },
    { label: "Mildew Resistance", value: "Guaranteed" },
    { label: "UV Resistance", value: "UV-stable — no degradation in Florida heat" },
    { label: "Compatible Substrates", value: "Clay tile, concrete tile, metal roofing, flat deck" },
    { label: "Product Warranty", value: "5 Years" },
    { label: "Manufactured", value: "Davie, Florida — RoofProtect" },
    { label: "Price", value: "$190 per 5-gallon pail" },
  ],
  applications: [
    "Tile roofs with black streaking and algae growth",
    "Roofs in high-humidity coastal and inland Florida climates",
    "HOA properties requiring uniform clean appearance",
    "Post-pressure-wash protective treatment",
    "Preventative treatment on new construction roofs",
    "Historic or aged tile roofs where preserving appearance matters",
    "Commercial flat roofs with surface mildew growth",
    "Roofs where prior biological damage has been remediated",
  ],
  faq: [
    {
      q: "Is Fungal Shield the same as bleach or pressure washing?",
      a: "No — pressure washing and bleach treatments kill surface growth temporarily but provide no lasting protection. Fungal Shield bonds to the tile surface and creates a permanent barrier against re-infestation. It also doesn't risk the tile damage that high-pressure washing can cause on aged tiles.",
    },
    {
      q: "Will Fungal Shield change the color or appearance of my tiles?",
      a: "Fungal Shield is a clear coating. Your tiles will look the same — just cleaner and free of biological staining. The coating is not visible to the eye after curing.",
    },
    {
      q: "How long does the 5-Year Warranty cover?",
      a: "The 5-Year Product Warranty covers the mildew resistance and waterproofing performance of the Fungal Shield coating against defects in the product. Actual biological protection performance in Florida conditions typically runs beyond the warranty period.",
    },
    {
      q: "Can Fungal Shield be combined with Smart Shield or Roof Shield?",
      a: "Yes — Fungal Shield is frequently applied as a base treatment before Smart Shield or Roof Shield, particularly on roofs with a history of biological growth. All three systems share compatible base chemistries and are designed to work together.",
    },
    {
      q: "Do you need to come out and inspect before applying?",
      a: "Yes — we provide a free over-the-phone or on-site evaluation to assess the condition of your roof, identify the biological growth present, and confirm Fungal Shield is the right product for your situation.",
    },
  ],
  relatedProducts: [
    { name: "Smart Shield", href: "/products/smartshield", desc: "Energy-reflective smart coating — our most popular system.", icon: Sun },
    { name: "Roof Shield", href: "/products/roofshield", desc: "Flagship all-weather waterproofing membrane — lifetime warranty.", icon: ShieldCheck },
  ],
  shopUrl: "https://www.roofprotectproducts.com/product/RP1FungalShield",
  price: "$190",
  shopAvailable: false,
  sku: "RP1",
  mpn: "RP1",
  productImage: `${BASE}/images/roofshield-bucket.webp`,
  pdfUrl: "/docs/roofprotect-brochure.pdf",
  pdfLabel: "RoofProtect Product Brochure (PDF)",
};

export const smartShield: ProductData = {
  slug: "smartshield",
  name: "Smart Shield",
  tagline: "Waterproof. Weatherproof. 3,000+ Colors. The Tintable Roof Coating Built for Florida Tile.",
  category: "RP2 — Tintable Waterproof & Weatherproof Tile Roof Coating",
  icon: Sun,
  accentColor: "text-accent",
  badgeColor: "bg-accent/10 text-accent",
  seoTitle: "Smart Shield (RP2) — Reflective Cool Roof Coating | The Roof Store",
  seoDescription: "Smart Shield is a reflective cool roof coating that waterproofs tile roofs in 3,000+ colors. The professional evolution of roof painting — 5× the thickness, true waterproofing, 3,000+ colors. BASF Cool Pigment means the darker the color, the more it reflects. Base can be elastomeric or polyurethane, or blended with ceramic for a flatter, less-reflective look. FP&L confirmed energy savings. Free quote — 954-210-9614.",
  heroDesc: "A full waterproof, weatherproof coating system for tile roofs — in over 3,000 tintable colors. As a reflective cool roof coating, the darker the color, the more it reflects. FP&L confirmed energy savings. Exclusively available through The Roof Store.",
  heroImage: `${BASE}/images/Waterproofing-Technology.jpg`,
  heroImageAlt: "Smart Shield RP2 waterproof cool roof coating applied to Florida tile roof — 3,000+ colors, BASF cool pigment",
  overview: [
    "Smart Shield (RP2) is RoofProtect Products' most popular system, available exclusively through The Roof Store — a complete waterproof and weatherproof roof coating engineered specifically for Florida tile roofs. Its base formula is typically elastomeric, tuned for darker tile colors, and it seals the tile surface against wind-driven rain, UV degradation, moisture intrusion, and mildew growth. It is 5× thicker than standard roof paint and bonds directly to the tile, forming a durable protective barrier that extends tile life significantly.",
    "Smart Shield's base can also be formulated as polyurethane instead of elastomeric, or blended with ceramic for a flatter, less-reflective look on tile roofs where a matte finish is preferred, or for certain flat roof applications — the right formulation depends on the roof deck's drainage and the project's price point. It is important to understand what Smart Shield is and is not. For the main field tiles, Smart Shield is a surface coating — it protects the tile face and waterproofs the roof without filling the spaces between individual tiles. That full gap-filling monolithic treatment is the job of our Roof Shield (RP3) system. Where Smart Shield does add structural reinforcement is at the ridge caps: during every installation, the ridge caps are polyurethaned and fiber coated as a minimum standard. Ridge caps are the most wind-vulnerable section of any tile roof in South Florida, and this treatment gives them meaningful additional hurricane wind-lift protection — even on a Smart Shield-only job.",
    "What sets Smart Shield apart from any other waterproof tile coating is its color capability. Over 3,000 tintable color options — and in collaboration with BASF, the world's largest chemical producer, RoofProtect engineered a breakthrough no other reflective roof coating has achieved: Cool Pigment Technology that increases Total Solar Reflectance (TSR) by 32%, even at the darkest black. The counterintuitive result: the darker the color you choose, the more heat this cool roof coating reflects. Florida Power & Light (FP&L) independently confirmed the energy savings. Manufactured by RoofProtect at their Davie, Florida facility — not available in any retail store.",
    "Smart Shield is the professional evolution of roof painting: the same idea of applying a protective color coat to a tile roof, but engineered to 5× the thickness of standard roof paint, formulated for true waterproofing rather than cosmetics, and backed by BASF-developed reflective chemistry no roof paint offers.",
  ],
  features: [
    { title: "Waterproof & Weatherproof Surface Coating", desc: "Seals the tile surface against wind-driven rain, UV damage, and moisture intrusion. 5× thicker than standard roof paint — bonds directly to field tile, not a thin decorative coat." },
    { title: "Ridge Caps — Polyurethane & Fiber Treatment", desc: "Every Smart Shield installation includes polyurethane and fiber coating on the ridge caps as a minimum standard. Ridge caps are the most wind-exposed area of any tile roof — this treatment provides meaningful hurricane wind-lift protection at the critical points." },
    { title: "3,000+ Tintable Colors", desc: "The widest color selection of any protective tile roof coating. Match any HOA color, existing tile shade, or custom aesthetic — exclusively formulated and manufactured by RoofProtect." },
    { title: "Reflective Cool Roof Coating — The Darker, the More Reflective", desc: "BASF-engineered Cool Pigment Technology increases Total Solar Reflectance (TSR) by 32% — even at the darkest black. As a true reflective cool roof coating, you choose the color you want without sacrificing energy performance." },
    { title: "Polyurethane Base or Ceramic Blend Available", desc: "For tile roofs that don't want a reflective finish, or for certain flat roof applications, Smart Shield's base can be formulated as polyurethane instead of elastomeric, or blended with ceramic for a flatter, less-reflective look — the right option depends on price point and roof deck drainage." },
    { title: "FP&L Confirmed Energy Savings", desc: "Florida Power & Light independently confirmed Smart Shield saves on cooling costs — the only utility-endorsed roof coating in our category." },
    { title: "Guaranteed Mildew Resistance", desc: "Biologically resistant formula — less cleaning, no black streaking, lasting curb appeal in Florida's humid climate." },
    { title: "Metal Roof Coating Option", desc: "Formulated to bond directly to metal roofing as a direct-to-metal roof coating — waterproofing, color, and reflectivity on metal panels, not just tile." },
    { title: "Rated for Ponding Water on Flat Roofs", desc: "Unlike many elastomeric roof paints that carry a 'not for use in ponding water' warranty exclusion, Smart Shield's silicone/polyurethane formulations are built to perform on flat decks where water sits." },
  ],
  specs: [
    { label: "Product Code", value: "RP2 — Smart Shield" },
    { label: "Primary Function", value: "Waterproof & weatherproof coating for tile, metal, and flat roofs" },
    { label: "Base Formula", value: "Elastomeric or polyurethane — ceramic blend available for a flatter, less-reflective look" },
    { label: "Color Options", value: "3,000+ tintable colors — full custom palette available" },
    { label: "Coverage Rate", value: "~90 sq ft per gallon" },
    { label: "Thickness", value: "5× thicker than standard roof paint" },
    { label: "Cool Pigment", value: "BASF Technology — TSR increased by 32% even at darkest black" },
    { label: "Energy Endorsement", value: "FP&L (Florida Power & Light) confirmed cooling cost savings" },
    { label: "Waterproofing", value: "Wind-driven rain resistant — rated for ponding water on flat decks" },
    { label: "Mildew Resistance", value: "Guaranteed" },
    { label: "Availability", value: "Exclusive — not available in any retail store" },
    { label: "Compatible Substrates", value: "Cement tile, clay tile, S-tile, flat tile, shingle, metal roofing" },
    { label: "Manufactured", value: "Davie, Florida — RoofProtect" },
    { label: "Price", value: "$285 per 5-gallon pail" },
  ],
  applications: [
    "Tile roofs needing waterproofing and weatherproofing protection — primary use case",
    "Homeowners who want a specific roof color (dark or light) without sacrificing protection",
    "South Florida homes with high monthly cooling bills seeking a tinted protective coating",
    "Any tile roof — cement tile, clay tile, barrel tile, S-tile",
    "HOA communities standardizing on a single approved color with maximum durability",
    "Post-storm roof restoration with color refresh and weatherproofing upgrade",
    "Coastal and sun-exposed roofs with maximum UV and moisture exposure",
    "Properties targeting FP&L or utility energy rebate programs",
  ],
  faq: [
    {
      q: "Does Smart Shield fill the gaps between tiles like Roof Shield does?",
      a: "No — and that's an important distinction. Smart Shield is a surface coating applied to the field tiles. It waterproofs and protects the tile face but does not fill the spaces between individual tiles. That full gap-filling monolithic treatment — where every void between tiles is sealed solid — is what Roof Shield (RP3) does. If your goal is maximum hurricane wind-lift protection across the entire roof field, Roof Shield is the right system. Smart Shield gives you excellent tile protection and color in a single coat.",
    },
    {
      q: "Does Smart Shield provide any hurricane protection?",
      a: "Yes, at the ridge caps. Every Smart Shield installation includes polyurethane and fiber coating on the ridge caps as a minimum standard. The ridge caps are the most vulnerable section of any tile roof to wind uplift in a South Florida hurricane — this treatment mechanically reinforces them and provides meaningful additional wind-lift protection. The field tiles receive the waterproof surface coating. For full monolithic hurricane protection across every tile, the Roof Shield system is the complete solution.",
    },
    {
      q: "What is Smart Shield actually for — is it paint or a waterproofer?",
      a: "Both. Smart Shield is first and foremost a waterproof weatherproof surface coating for tile roofs — it seals the tile face against rain, UV, and moisture. It comes in over 3,000 tintable colors with BASF Cool Pigment energy-reflectance built in. Think of it as complete tile protection in your chosen color.",
    },
    {
      q: "How can a dark color reflect MORE heat than a lighter one?",
      a: "This is the breakthrough RoofProtect's collaboration with BASF produced. Standard dark pigments absorb heat — that's why everyone assumed dark roofs would always be hotter. Our Cool Pigment Technology uses specially engineered near-infrared-reflective (NIR) pigments that bounce away the sun's heat energy even in the darkest color ranges. TSR is increased by 32% across all colors, with the greatest gain at the darkest end of the spectrum. No other coating achieves this.",
    },
    {
      q: "Can Smart Shield be made non-reflective for tile roofs that don't want that effect?",
      a: "Yes — Smart Shield's base can be formulated as polyurethane instead of elastomeric, or blended with ceramic for a flatter, less-reflective look, for tile roofs where a matte finish is preferred, or for certain flat roof applications. Which formulation makes sense depends on your price point and the roof deck's drainage. We'll recommend the right formulation during your free evaluation.",
    },
    {
      q: "How many colors does Smart Shield come in?",
      a: "Over 3,000 tintable color options. We work with you to match any HOA-approved color, any existing tile, or any custom aesthetic. Because RoofProtect manufactures the product, we can produce the exact formulation for your project — something no retail paint store can do.",
    },
    {
      q: "Is Smart Shield available at Home Depot, Lowe's, or any other retailer?",
      a: "No. Smart Shield is an exclusive proprietary formula developed by RoofProtect in collaboration with BASF, available through The Roof Store. It is not sold in any retail store, hardware chain, or through any other contractor. The only way to get it is directly through us.",
    },
    {
      q: "Can Smart Shield be applied over Fungal Shield?",
      a: "Yes — we frequently apply Fungal Shield first as a biocide base treatment, then Smart Shield over it for combined weatherproofing, color, and biological protection. The products are fully compatible and designed to work together as a system.",
    },
  ],
  relatedProducts: [
    { name: "Fungal Shield", href: "/products/fungalshield", desc: "Anti-fungal & anti-algae coating — eliminate black streaking.", icon: Leaf },
    { name: "Roof Shield", href: "/products/roofshield", desc: "Flagship all-weather waterproofing membrane — lifetime warranty.", icon: ShieldCheck },
  ],
  shopUrl: "https://www.roofprotectproducts.com/product/RP2SmartShield",
  price: "$285",
  shopAvailable: true,
  sku: "RP2",
  mpn: "RP2",
  productImage: `${BASE}/images/roofshield-bucket.webp`,
  pdfUrl: "/docs/roofprotect-product-presentation.pdf",
  pdfLabel: "RoofProtect Product Presentation (PDF)",
  galleryImages: [
    {
      src: `/api/storage/public-objects/smartshield/ss-tile-repair-before.png`,
      alt: "Broken roof tile before Smart Shield repair — open valley damage",
      caption: "Tile repair — before",
    },
    {
      src: `/api/storage/public-objects/smartshield/ss-tile-repair-step2.png`,
      alt: "Roof tile repair in progress — fiber coat pointing applied",
      caption: "Tile repair — in progress",
    },
    {
      src: `/api/storage/public-objects/smartshield/ss-tile-repair-step3.png`,
      alt: "Roof tile repair complete — residue wiped, surface ready for coating",
      caption: "Tile repair — complete",
    },
    {
      src: `/api/storage/public-objects/smartshield/ss-softwash-truck.jpg`,
      alt: "Chemical soft wash truck with water tank used for roof cleaning in Florida",
      caption: "Soft wash system — water truck",
    },
    {
      src: `/api/storage/public-objects/smartshield/ss-softwash-pressure.jpg`,
      alt: "Soft wash truck and pressure cleaning equipment on Florida roofing job",
      caption: "Soft wash system — equipment",
    },
    {
      src: `/api/storage/public-objects/smartshield/ss-softwash-tool.jpg`,
      alt: "Soft wash cleaning tool applied to tile roof surface",
      caption: "Soft wash tool on roof",
    },
    {
      src: `/api/storage/public-objects/smartshield/ss-softwash-cleaning.jpg`,
      alt: "Technician performing chemical soft wash on tile roof",
      caption: "Technician soft washing roof",
    },
    {
      src: `/api/storage/public-objects/smartshield/ss-open-valleys.png`,
      alt: "Adding waterproofing to open valleys on tile roof — Smart Shield prep step",
      caption: "Prep — waterproofing open valleys",
    },
    {
      src: `/api/storage/public-objects/smartshield/ss-ridge-caps.png`,
      alt: "Ridge caps polyurethaned and pointings fiber coated on tile roof — Smart Shield prep",
      caption: "Prep — ridge caps polyurethaned & fiber coated",
    },
    {
      src: `${BASE}/images/projects/spanish-tile-extra-3.png`,
      alt: "Composite tile roof coated with Smart Shield color roof system",
      caption: "Completed project — Smart Shield color system",
    },
    {
      src: `${BASE}/images/projects/spanish-tile-extra-4.png`,
      alt: "Composite tile roof restoration with Smart Shield cool pigment coating",
      caption: "Completed project — cool pigment restored tile",
    },
  ],
};

export const roofShield: ProductData = {
  slug: "roofshield",
  name: "Roof Shield",
  tagline: "We Don't Just Coat Your Roof — We Make It Monolithic. No Gaps. No Seams. Hurricane Proof.",
  category: "RP3 — Multi-Layer Monolithic Hurricane Roof System",
  icon: ShieldCheck,
  accentColor: "text-primary",
  badgeColor: "bg-primary/10 text-primary",
  seoTitle: "Roof Shield (RP3) — Liquid Applied Rubber System | The Roof Store",
  seoDescription: "Roof Shield — The Original Liquid Applied Rubber Roof Shield System — fills every gap and void between your tiles with multiple product layers — making your roof monolithic. The professional evolution of roof painting — monolithic, hurricane-rated, lifetime warranty. Typically formulated with a silicone base for all roof types, including flat roofs that hold water. TAS-106 rated, 5× stronger, lifetime warranty. 954-210-9614.",
  heroDesc: "A multi-layer system using several of our proprietary products to fill every space between your tiles — creating a single monolithic roof structure. No gaps. No wind or rain entry. The world's only liquid roof coating to pass the Dade County Certified TAS-106 Uplift Pull Test.",
  heroImage: `${BASE}/images/roof-shield-system.jpg`,
  heroImageAlt: "Roof Shield RP3 liquid applied rubber roof system — multi-layer monolithic hurricane coating, passed the Dade County Certified TAS-106 Uplift Test, Davie Florida",
  overview: [
    "Roof Shield (RP3) — officially The Original Liquid Applied Rubber Roof Shield System — is fundamentally different from any roof coating on the market, because it is not just a coating. It is a multi-layer system that uses several of RoofProtect's proprietary products in combination to physically fill every void, gap, and space between your tiles: under the overlaps, in the grout joints, between barrel tile ribs, in every penetration point. Before treatment, your tile roof has hundreds of open spaces that wind and rain can enter. After Roof Shield, those spaces are gone — sealed solid.",
    "Roof Shield, Smart Shield, and Fungal Shield are interchangeable systems built from elastomeric, polyurethane, or silicone base ingredients depending on a customer's goals and price point. Roof Shield specifically is usually formulated around a proprietary premium silicone base ingredient to achieve its monolithic barrier — which is what makes it suitable for every roof type, including flat roofs that hold standing water. The result is a monolithic roof: instead of hundreds of individual tiles sitting on mortar and clips — each one a potential wind or water entry point — the entire roof surface becomes one continuous sealed structure. Wind cannot lift individual tiles because they are bonded into a single unit. Rain cannot penetrate between tiles because there are no gaps left to enter. Before and after photos of the process show the dramatic difference: tile voids that were once open to the sky are completely filled and sealed.",
    "This multi-layer monolithic system is the reason Roof Shield is the only liquid roof coating ever to pass the independent Dade County Certified TAS-106 Uplift Pull Test — 5× the wind uplift strength of a new tile roof, at approximately half the replacement cost, with a maintenance-free Lifetime Warranty that is transferable and renewable.",
    "Roof Shield is the professional descendant of the tile-securing technique roof painters discovered decades ago — refined, warrantied, and engineered specifically to fill every gap between tiles rather than just coat the surface. When completed, it is a seamless coating system — one continuous membrane over the entire roof, with no joints, no seams, and no weak points.",
    "This is also why Roof Shield changes the conversation about tile roof leaks. In a traditional tile roof, the tiles shed water while a paper or synthetic underlayment beneath them does the real waterproofing — and when that underlayment tears, the standard industry answer is an invasive 'tile lift-and-reset': removing tiles, replacing the paper, and resetting the tiles, a disturbance that frequently creates new cracked tiles and new leaks unless you're committed to a full tile replacement project. Roof Shield takes a fundamentally different path: because the completed system seals the entire roof surface into one seamless waterproof membrane above the tiles, the roof no longer depends on the aging underlayment as its only water barrier. On a structurally sound roof — after every cracked tile and defect is repaired as part of the process — RP3 is far superior to any traditional roof material application, including synthetics: it is the answer that avoids tearing your roof apart to fix what's under it.",
  ],
  features: [
    { title: "The Original Liquid Applied Rubber Roof Shield System", desc: "Roof Shield uses several proprietary products in multiple application layers to fill and seal every gap between tiles. The before/after transformation is visible to the eye." },
    { title: "Monolithic Roof Structure", desc: "After Roof Shield, your tile roof is no longer individual pieces — it is one continuous sealed unit. Wind cannot get under individual tiles. Rain has no gaps to enter through." },
    { title: "Proprietary Premium Silicone Base", desc: "Roof Shield is usually formulated around a proprietary premium silicone base ingredient — well suited to every roof type, including flat roofs that hold standing water. Our systems can also interchange elastomeric or polyurethane ingredients depending on the project's goals and price point." },
    { title: "Every Gap and Void Filled — Completely", desc: "Under overlaps, in grout joints, between barrel tile ribs, around all penetrations — every space is filled. No entry points remain for wind or water." },
    { title: "World's Only Coating to Pass the TAS-106 Test", desc: "The only roof coating system worldwide to pass the Dade County Certified TAS-106 Uplift Pull Test — the same standard required for new tile installations. Originally passed in 2006." },
    { title: "135+ MPH Documented Wind Resistance — 5× Stronger", desc: "Not simulated — real documented hurricane projects where treated roofs did not lose a single tile. 5× the wind uplift resistance of a new tile roof at up to 60–70% less cost." },
    { title: "Lifetime Product Warranty", desc: "Maintenance-free. Transferable to a new buyer when the property sells. Renewable. No standard new roof warranty offers all three." },
    { title: "Insurance Inspection Readiness", desc: "Florida homeowners have the legal right, per state statute, to request an independent Useful Life Exam. We help get your roof into its best possible condition before the inspector arrives — cleaned, repaired, and professionally coated. A well-maintained roof gives the insurance company very little to work with beyond age alone." },
    { title: "Rated for Ponding Water — Flat Roof Coating", desc: "Many generic roof paints and elastomeric coatings carry a 'not for use in ponding water' warranty exclusion, disqualifying them from flat roofs. Roof Shield's silicone-based formulation is built specifically to perform on flat decks where water sits after rain." },
    { title: "Full Metal Roof Coverage", desc: "Beyond tile, Roof Shield's multi-layer system applies to metal roofing as well — sealing seams and fasteners on metal panels the same way it seals tile gaps." },
  ],
  specs: [
    { label: "Product Code", value: "RP3 — Roof Shield" },
    { label: "System Name", value: "The Original Liquid Applied Rubber Roof Shield System" },
    { label: "System Type", value: "Multi-layer monolithic roof system — multiple products applied in sequence" },
    { label: "Base Ingredient", value: "Proprietary premium silicone blend (interchangeable with elastomeric or polyurethane by project)" },
    { label: "Key Mechanism", value: "Fills every gap and void between tiles — creates one continuous sealed roof structure" },
    { label: "Coverage Rate", value: "~50 sq ft per gallon (full multi-layer membrane)" },
    { label: "Wind Rating", value: "135+ MPH — documented real hurricane performance" },
    { label: "TAS-106 Test", value: "Passed the Dade County Certified TAS-106 Uplift Pull Test — only liquid coating worldwide to do so" },
    { label: "Wind Strength", value: "5× stronger than a new tile roof in uplift resistance" },
    { label: "Warranty", value: "Lifetime — Maintenance-Free, Transferable & Renewable" },
    { label: "Roof Life Extension", value: "Up to 10 additional years certification (State of Florida / Citizens recognized)" },
    { label: "Ponding Water Rating", value: "Rated for standing/ponding water on flat roofs — no exclusion" },
    { label: "Compatible Substrates", value: "Concrete tile, barrel tile, S-tile, flat deck (including water-holding flat roofs), metal roofing, gravel, foam — any Florida roof" },
    { label: "Manufactured", value: "Davie, Florida — RoofProtect" },
    { label: "Price", value: "$325 per 5-gallon pail" },
  ],
  applications: [
    "Tile roofs where individual tiles are at risk of wind uplift in hurricane conditions",
    "Any tile roof where gaps between tiles allow rain or wind intrusion",
    "Roofs approaching or past replacement age that need a structural solution",
    "Flat decks and low-slope roofs with chronic or active leaks",
    "Properties in hurricane-prone zones requiring documented wind resistance",
    "Insurance-restoration projects — Citizens and other carrier accepted",
    "Roofs needing Additional Roof Life Certification for insurance continuation",
    "Post-hurricane storm damage restoration and reinforcement",
  ],
  faq: [
    {
      q: "What does 'monolithic roof' actually mean?",
      a: "A monolithic roof is one continuous sealed structure — instead of hundreds of individual tiles with gaps between them. Roof Shield fills every void and space between your tiles with multiple layers of product. After installation, your tile roof behaves as a single unit: wind cannot get under individual tiles to lift them, and rain cannot penetrate through the spaces between tiles because those spaces no longer exist. Before/after photos of the process make this immediately clear.",
    },
    {
      q: "What is Roof Shield actually made of — rubber or silicone?",
      a: "Roof Shield is officially The Original Liquid Applied Rubber Roof Shield System — that's the name of the system. The specific base ingredient RoofProtect typically formulates it with is a proprietary premium silicone blend, chosen because it performs on every roof type, including flat roofs that hold standing water. Our systems can also interchange elastomeric or polyurethane base ingredients depending on a project's goals and price point.",
    },
    {
      q: "How many products are used in the Roof Shield system?",
      a: "Roof Shield is a multi-layer system that uses several of RoofProtect's proprietary products applied in sequence. Each layer serves a specific function — penetrating seal, gap fill, bonding membrane, and protective topcoat — working together to create the final monolithic structure. This is why you cannot replicate the result with a single off-the-shelf product.",
    },
    {
      q: "I have a tile roof leak — do I need a 'tile lift-and-reset' underlayment repair?",
      a: "Often, no — and that is exactly what makes the Roof Shield system different. Understand what a 'lift-and-reset' really is: re-roofing by another name. The tiles come off, new material goes underneath, and the tiles go back on — that is a partial re-roof, marketed as a 'repair.' Don't re-roof when you don't have to. In a traditional tile roof, water passes between the tiles onto underlayment paper below, and when that paper tears, the industry's answer is to start taking your roof apart. It's invasive, and it commonly creates new broken tiles and new leaks unless you're committed to a full tile replacement. Roof Shield eliminates the need for that in most structurally sound roofs: our liquid rubber flows into and fills every gap between the tiles, and when completed the roof is one seamless coating system — a continuous waterproof membrane above the tiles, so the roof no longer relies on the old underlayment as its only water barrier. Every job starts with an inspection and repair of cracked tiles and defects before coating. The one exception — discovered while undertaking our full onsite Manufacturer's Inspection Report (prepared for every Roof Shield (RP3) request; other services receive an onsite evaluation, not the full report): any rotten or soft wood underneath the tile must be repaired first (tiles in that localized area are lifted, the bad piece of wood is removed and dried back in with traditional materials), and then the coating system proceeds over the sound roof. As our Manufacturer's Inspection Report states: 'The Manufacturer's Inspection is not intended to provide structural integrity advice. The purpose of this review of your roof is to confirm stable surfaces of your flat roof or roof tiles; that the flat deck or tile attachments are secure; to identify the presence of any chips or cracks; that flat deck tie-ins, seams, and edges are secure; and that all returns, eaves, and soffits are free of rot from moisture and water intrusion. Any insulation or wood that may be soft or wet — and dangerous to walk on — must be repaired prior to the application of roof coatings. The main purpose of this inspection is the future successful application of our products, which require the roof surfaces to be traversed to apply protective coatings. You may be alerted to rework areas or other concerns that should be addressed. The owner is ultimately responsible for any repairs or rework indicated prior to application (unless otherwise specified and included depending on scope) of our roof coatings and/or roof maintenance systems, which may be at an additional cost above the standard application costs for the installation of our products.' RP3 is far superior to any traditional roof material application, including synthetic underlayments — it is the answer, not the patch. And among roof coating systems, RP3 is more applicable to this problem than any other, period: it is the only one engineered as a monolithic system — and the only one to pass the Dade County Certified TAS-106 Uplift Test as a system, not just a surface coat.",
    },
    {
      q: "Does The Roof Store sell synthetic roofing underlayment?",
      a: "No. The Roof Store and RoofProtect Products have never manufactured or sold synthetic roofing underlayment — our approach makes it unnecessary. The Roof Shield (RP3) system seals the entire roof surface into one seamless monolithic membrane, so the roof no longer depends on underlayment paper as its water barrier at all. Any 'synthetic roofing underlayment' advertised under a similar name is not our product and is not affiliated with The Roof Store of Davie, FL (theroofstore.net).",
    },
    {
      q: "What makes Roof Shield different from any other roof coating?",
      a: "Most roof coatings go over the surface of tiles — they do not fill the spaces between them. Roof Shield fills the voids, gaps, and overlaps between tiles, transforming a collection of individual pieces into one sealed roof structure. That's why it is the world's only liquid coating to pass the Dade County Certified TAS-106 Uplift Pull Test — because no other product has achieved what Roof Shield does structurally.",
    },
    {
      q: "How does 5× stronger than a new roof actually work?",
      a: "A new tile roof passes TAS-106 at approximately 35–55 lbs of uplift force. Roof Shield-treated roofs pull-test at 5× those values because the tiles are no longer individual pieces — they are bonded into a monolithic structure. Wind uplift force that would displace a single tile has no effect when that tile is mechanically fused to every tile around it and to the substrate beneath.",
    },
    {
      q: "What does the Lifetime Warranty cover?",
      a: "The Lifetime Product Warranty covers the Roof Shield system against product failure. It is maintenance-free, transferable to a new buyer when the property sells, and renewable. No standard new roof warranty offers all three.",
    },
    {
      q: "Will this qualify my old roof for insurance continuation?",
      a: "Yes — by being proactive. Under Florida law, homeowners have the legal right to request an independent Useful Life Exam on their roof. It is the report from that licensed inspector — not any product or contractor — that the insurance company recognizes for coverage continuation. What Roof Shield does is put your roof in its best possible condition before that exam: sealed, waterproofed, and demonstrably well-maintained. When the inspector arrives, a roof in good condition gives the insurer very little to work with beyond the age of the roof alone.",
    },
    {
      q: "How much cheaper is this than replacing my roof?",
      a: "Roof Shield typically costs 60–70% less than a full tile roof replacement — while delivering 5× the wind uplift resistance and a monolithic structure no new roof can match. Most residential projects save $20,000–$80,000. Call us for a free evaluation.",
    },
  ],
  relatedProducts: [
    { name: "Fungal Shield", href: "/products/fungalshield", desc: "Anti-fungal & anti-algae coating — eliminate black streaking.", icon: Leaf },
    { name: "Smart Shield", href: "/products/smartshield", desc: "Energy-reflective smart coating — FP&L confirmed savings.", icon: Sun },
  ],
  shopUrl: "https://www.roofprotectproducts.com/product/RP3RoofShield",
  price: "$325",
  shopAvailable: true,
  sku: "RP3",
  mpn: "RP3",
  certificationUrl: "/tas-106-certified-roof-coating",
  certificationLabel: "Dade County Certified TAS-106 Uplift Test — Full Reference Page",
  productImage: `${BASE}/images/roofshield-bucket.webp`,
  pdfUrl: "/docs/roofshield-strength-data-sheet.pdf",
  pdfLabel: "RoofShield Strength Data Sheet (PDF)",
  beforeAfterImages: [
    {
      label: "Preparation — We Retrofit a Monolithic Seamless System: Fill All Field Spaces, Ridge Caps & Open Valleys",
      before: `/api/storage/public-objects/roofshield/rs-prep-1-before.jpg`,
      beforeAlt: "Roof Shield preparation — filling open valleys between tiles with coating",
      after: `/api/storage/public-objects/roofshield/rs-prep-2-after.jpg`,
      afterAlt: "Ridge caps sealed with polyurethane as part of Roof Shield multi-layer system",
    },
    {
      label: "Top Coat — Job Completed",
      before: `/api/storage/public-objects/roofshield/rs-prep-3-before.jpg`,
      beforeAlt: "Roof before final Roof Shield top coat application",
      after: `/api/storage/public-objects/roofshield/rs-prep-4-after.jpg`,
      afterAlt: "Roof after Roof Shield top coat — monolithic sealed surface, job completed",
    },
    {
      label: "Composite Clay Tile Roof",
      before: `${BASE}/images/projects/clay-tile-before.png`,
      beforeAlt: "Composite clay tile roof before Roof Shield — visible gaps and voids between tiles",
      after: `${BASE}/images/projects/clay-tile-after.png`,
      afterAlt: "Composite clay tile roof after Roof Shield — all gaps sealed, monolithic surface",
    },
    {
      label: "Flat Cement Tile Roof",
      before: `${BASE}/images/projects/flat-cement-before.png`,
      beforeAlt: "Flat cement tile roof before Roof Shield — open spaces between tiles",
      after: `${BASE}/images/projects/flat-cement-after.png`,
      afterAlt: "Flat cement tile roof after Roof Shield — every space between tiles sealed solid",
    },
    {
      label: "Spanish Tile Roof",
      before: `${BASE}/images/projects/spanish-tile-before.png`,
      beforeAlt: "Composite Spanish tile roof before Roof Shield — visible gaps between tiles",
      after: `${BASE}/images/projects/spanish-tile-after.png`,
      afterAlt: "Composite Spanish tile roof after Roof Shield — monolithic sealed surface",
    },
    {
      label: "Flat Deck Roof",
      before: `${BASE}/images/projects/flat-deck-before-2.png`,
      beforeAlt: "Commercial built-up flat deck roof before Roof Shield waterproof coating",
      after: `${BASE}/images/projects/flat-deck-after-2.png`,
      afterAlt: "Commercial built-up flat deck roof fully restored after Roof Shield waterproof coating",
    },
    {
      label: "Flat Roof Retrofit — All Seams Taped to Create a Monolithic Seamless System",
      before: `/api/storage/public-objects/roofshield/rs-flat-seams-before.png`,
      beforeAlt: "Flat roof during Roof Shield retrofit — all seams taped to create a monolithic seamless system",
      after: `/api/storage/public-objects/roofshield/rs-flat-coated-after.png`,
      afterAlt: "Flat roof after Roof Shield retrofit — fully coated monolithic seamless waterproof system completed",
    },
  ],
};

export const productMap: Record<string, ProductData> = {
  fungalshield: fungalShield,
  smartshield: smartShield,
  roofshield: roofShield,
};
