// CONFIDENTIAL — draft federal complaint. Served ONLY through the authenticated
// /trademark-monitoring/case-file/complaint endpoint. Never import from client code.
// Source: owner's drafted complaint (uploaded Aug 2, 2026), reconstructed with
// paragraph numbering restored (the uploaded .docx lost its formatting in export).

export const COMPLAINT_HTML = `
<div class="complaint-doc" style="line-height:1.7;">
<style>
.complaint-doc h2{font-size:1.05rem;font-weight:700;text-align:center;margin:2rem 0 1rem;text-transform:uppercase;letter-spacing:.03em;}
.complaint-doc h3{font-size:.95rem;font-weight:700;text-align:center;margin:1.6rem 0 .8rem;}
.complaint-doc p{margin:.7rem 0;}
.complaint-doc .num{font-weight:700;margin-right:.35rem;}
.complaint-doc .fill{background:#fef9c3;padding:0 .15rem;border-radius:2px;}
.complaint-doc a{color:#1d4ed8;text-decoration:underline;}
.complaint-doc ol.relief{margin:.5rem 0 .5rem 1.5rem;list-style:lower-alpha;}
.complaint-doc ol.relief li{margin:.45rem 0;}
</style>

<p style="background:#fff7ed;border:1px solid #fdba74;border-radius:8px;padding:.8rem 1rem;font-size:.85rem;"><strong>DRAFT — for attorney review only.</strong> This is a sample complaint prepared in case the matter proceeds to federal court after the UDRP/ICANN domain proceeding. Yellow-highlighted brackets must be completed by counsel before filing (entity type, defendant's identity, counsel signature block). Case citations link to the research source for verification.</p>

<h2>United States District Court<br/>Southern District of Florida</h2>
<p style="text-align:center;">Case No. <span class="fill">[&nbsp;&nbsp;&nbsp;&nbsp;]</span></p>
<p><strong>THE ROOF STORE</strong>, a <span class="fill">[Florida corporation/LLC — entity type to be confirmed]</span>,<br/>&emsp;&emsp;Plaintiff,<br/>v.<br/><span class="fill">[DEFENDANT — the registrant and operator of the domain name theroof.store, and any known d/b/a or entity]</span>,<br/>&emsp;&emsp;Defendant.</p>

<h2>Complaint</h2>

<h3>Introduction</h3>
<p><span class="num">1.</span>This is an action for federal trademark infringement, false designation of origin, federal unfair competition, cybersquatting, and common law trademark infringement and unfair competition. This action arises from Defendant&rsquo;s bad-faith registration and use of the domain name theroof.store and its deliberate adoption of Plaintiff&rsquo;s exact trade name, THE ROOF STORE, as a product title to trade on Plaintiff&rsquo;s goodwill and cause consumer confusion.</p>

<h3>Parties</h3>
<p><span class="num">2.</span>Plaintiff The Roof Store is a <span class="fill">[entity type]</span> organized and existing under the laws of the State of Florida, with its principal place of business in Broward County, Florida. Plaintiff has used the trade name &ldquo;The Roof Store&rdquo; continuously in commerce since 1994 in connection with the sale of roofing materials and related services.</p>
<p><span class="num">3.</span>Upon information and belief, Defendant <span class="fill">[DEFENDANT NAME]</span> is <span class="fill">[the registrant and operator of theroof.store, and/or an individual or entity engaged in the sale of roofing materials, with residence/principal place of business unknown at this time — TO BE FILLED IN BY PLAINTIFF]</span>.</p>
<p><span class="num">4.</span>Upon information and belief, Defendant registered the domain name theroof.store on or about August 13, 2021, and uses it to market and sell competing roofing products into this judicial district.</p>

<h3>Jurisdiction and Venue</h3>
<p><span class="num">5.</span>This Court has subject matter jurisdiction over Plaintiff&rsquo;s federal claims pursuant to 15 U.S.C. &sect; 1121 and 28 U.S.C. &sect;&sect; 1331 and 1338(a), as this action arises under the Federal Trademark Act of 1946 (the Lanham Act), 15 U.S.C. &sect; 1051 et seq., and the Anticybersquatting Consumer Protection Act (ACPA), 15 U.S.C. &sect; 1125(d).</p>
<p><span class="num">6.</span>This Court has supplemental jurisdiction over Plaintiff&rsquo;s state and common-law claims pursuant to 28 U.S.C. &sect; 1367, as those claims are so related to the federal claims that they form part of the same case or controversy and derive from a common nucleus of operative fact.</p>
<p><span class="num">7.</span>Venue is proper in this District under 28 U.S.C. &sect; 1391(b) and (c) because Defendant resides in, transacts business in, and/or has committed acts giving rise to this action in this District; a substantial part of the events or omissions giving rise to the claims occurred in this District; and Plaintiff resides in this District. Defendant markets and sells competing products into Florida, including South Florida, where Plaintiff&rsquo;s business is located and where the consumer confusion documented herein occurred.</p>

<h3>Factual Allegations</h3>
<p><span class="num">8.</span>For more than three decades, Plaintiff has been a trusted provider of roofing materials and services in South Florida. Plaintiff began using the trade name THE ROOF STORE in commerce in 1994 and has used it continuously and exclusively in its market ever since.</p>
<p><span class="num">9.</span>On July 29, 2002, Plaintiff registered the domain name theroofstore.net. Per records from the Internet Archive, Plaintiff has maintained a continuous web presence under its mark since at least April 2001, establishing a nearly two-decade digital footprint before Defendant&rsquo;s infringing conduct began.</p>
<p><span class="num">10.</span>Plaintiff operates a substantial physical facility and factory in Broward County, Florida, under THE ROOF STORE name.</p>
<p><span class="num">11.</span>Through its long and exclusive use, Plaintiff has developed significant goodwill and brand recognition in its mark. Plaintiff maintains a verified Google Business Profile, enjoys decades of established customer relationships in South Florida, and has created an indexed body of web content under its mark.</p>
<p><span class="num">12.</span>On or about August 13, 2021 — more than 27 years after Plaintiff commenced use of its mark — Defendant registered the domain name theroof.store, which is confusingly similar to Plaintiff&rsquo;s mark and senior domain name.</p>
<p><span class="num">13.</span>Defendant had actual knowledge of Plaintiff and its senior rights in THE ROOF STORE mark prior to and during its infringing conduct. On July 28, 2026, Defendant sent a direct commercial solicitation to Plaintiff&rsquo;s business address, demonstrating that Defendant knew of Plaintiff&rsquo;s existence, its trade name, and its line of business. A true and correct copy of this solicitation is attached hereto as <strong>Exhibit S</strong>.</p>
<p><span class="num">14.</span>Defendant uses theroof.store to market and sell competing roofing products directly into the State of Florida, including in South Florida, the precise geographic market where Plaintiff&rsquo;s common-law rights are strongest and where Plaintiff&rsquo;s business and customers are located.</p>
<p><span class="num">15.</span>Plaintiff&rsquo;s mark has achieved such a high degree of marketplace recognition that Google&rsquo;s AI systems associate the mark &ldquo;The Roof Store&rdquo; with Plaintiff&rsquo;s single company profile, demonstrating that the mark functions as a source identifier, not a generic description.</p>
<p><span class="num">16.</span>Defendant&rsquo;s infringement has caused actual consumer confusion. As documented in <strong>Exhibit T</strong>, a consumer in South Florida performing a query about Spanish tile roofing — a specialty of Plaintiff — received an AI-generated response that misattributed Defendant&rsquo;s product details to Plaintiff. The response contained technical specifications, including &ldquo;ASTM D8257&rdquo; and &ldquo;Florida Approval # 48228,&rdquo; which match Defendant&rsquo;s own published product listing verbatim.</p>
<p><span class="num">17.</span>In a blatant act of passing off, Defendant has titled one of its own products &ldquo;The Roof Store Synthetic Roofing Underlayment.&rdquo; A true and correct copy of a webpage showing this product title is attached as <strong>Exhibit U</strong>. This product title embeds Plaintiff&rsquo;s exact trade name into a product offered in direct competition with Plaintiff, deliberately calculated to trade on Plaintiff&rsquo;s goodwill and deceive consumers.</p>

<h3>First Claim for Relief<br/><span style="font-weight:400;">(Trademark Infringement and False Designation of Origin in Violation of Section 43(a) of the Lanham Act, 15 U.S.C. &sect; 1125(a))</span></h3>
<p><span class="num">18.</span>Plaintiff incorporates by reference all preceding paragraphs as if fully set forth herein.</p>
<p><span class="num">19.</span>Section 43(a) of the Lanham Act prohibits the use in commerce of any word, term, name, symbol, or device, or any false designation of origin, which is likely to cause confusion, or to cause mistake, or to deceive as to the affiliation, connection, or association of such person with another person, or as to the origin, sponsorship, or approval of his or her goods, services, or commercial activities by another person. 15 U.S.C. &sect; 1125(a); see <a href="https://www.cetient.com/case/thoip-v-walt-disney-co-2401347" target="_blank" rel="noopener">THOIP v. Walt Disney Co.</a>, 690 F. Supp. 2d 218, 227 (S.D.N.Y. 2010).</p>
<p><span class="num">20.</span>To prevail on a claim under Section 43(a) for an unregistered mark, a plaintiff must show that (1) it has a valid trademark entitled to protection, and (2) the defendant&rsquo;s use of the mark infringes by causing a likelihood of confusion. See <a href="https://www.cetient.com/case/jewish-sephardic-yellow-pages-ltd-v-dag-media-inc-2575104" target="_blank" rel="noopener">Jewish Sephardic Yellow Pages, Ltd. v. DAG Media, Inc.</a>, 478 F. Supp. 2d 340, 351 (E.D.N.Y. 2007). For a descriptive mark, validity is established by showing that the mark has acquired secondary meaning. See <a href="https://www.cetient.com/case/wh-brady-co-v-lem-products-inc-8904922" target="_blank" rel="noopener">W.H. Brady Co. v. Lem Products, Inc.</a>, 659 F. Supp. 1355, 1359 (N.D. Ill. 1987).</p>
<p><span class="num">21.</span>Plaintiff&rsquo;s mark, THE ROOF STORE, has acquired secondary meaning and is therefore a valid, protectable mark. Through over 30 years of continuous and exclusive use in its market, the mark has come to identify Plaintiff as the unique source of the goods and services offered thereunder. See <a href="https://www.cetient.com/case/in-re-seats-inc-449360" target="_blank" rel="noopener">In Re Seats, Inc.</a>, 757 F.2d 274 (Fed. Cir. 1985); <a href="https://www.cetient.com/case/in-re-bush-brothers-company-528556" target="_blank" rel="noopener">In Re Bush Brothers &amp; Company</a>, 884 F.2d 569 (Fed. Cir. 1989); <a href="https://www.cetient.com/case/application-of-the-chesapeake-corporation-of-virginia-288029" target="_blank" rel="noopener">Application of the Chesapeake Corporation of Virginia</a>, 420 F.2d 754 (C.C.P.A. 1970).</p>
<p><span class="num">22.</span>Defendant&rsquo;s domain name, theroof.store, and its product title, &ldquo;The Roof Store Synthetic Roofing Underlayment,&rdquo; are identical or confusingly similar to Plaintiff&rsquo;s THE ROOF STORE mark.</p>
<p><span class="num">23.</span>Defendant&rsquo;s use of Plaintiff&rsquo;s mark is likely to cause, and has already caused, confusion, mistake, and deception among consumers as to the origin, sponsorship, or approval of Defendant&rsquo;s goods. This is evidenced by the actual confusion documented in Exhibit T, which occurred at the moment of a purchase decision and resulted in the displacement of Plaintiff&rsquo;s product with Defendant&rsquo;s. Unlike cases involving mere misdirected inquiries, this confusion inflicted a direct commercial injury. See <a href="https://www.cetient.com/case/lion-aire-corp-v-lion-air-installation-inc-10192667" target="_blank" rel="noopener">Lion-Aire Corp. v. Lion Air Installation, Inc.</a>, No. 22-CV-05047, 2024 WL 13490795, at *6 (E.D.N.Y. Aug. 27, 2024); cf. <a href="https://www.cetient.com/case/sunenblick-v-harrell-1570620" target="_blank" rel="noopener">Sunenblick v. Harrell</a>, 895 F. Supp. 616 (S.D.N.Y. 1995); <a href="https://www.cetient.com/case/rvc-floor-decor-ltd-v-floor-decor-holdings-inc-9842702" target="_blank" rel="noopener">RVC Floor Decor, Ltd. v. Floor &amp; Decor Holdings, Inc.</a>, No. 19-CV-04192, 2023 WL 2388701 (E.D.N.Y. Mar. 7, 2023).</p>
<p><span class="num">24.</span>Defendant&rsquo;s use of the mark also creates initial interest confusion, which is actionable under the Lanham Act. See <a href="https://www.cetient.com/case/jenzabar-inc-v-long-bow-group-inc-6589843" target="_blank" rel="noopener">Jenzabar, Inc. v. Long Bow Group, Inc.</a>, 82 Mass. App. Ct. 648 (2012).</p>
<p><span class="num">25.</span>Defendant&rsquo;s conduct constitutes an unfair and fraudulent advantage taken to pass off its products as those of Plaintiff. See <a href="https://www.cetient.com/case/american-chicle-co-v-topps-chewing-gum-inc-233477" target="_blank" rel="noopener">American Chicle Co. v. Topps Chewing Gum, Inc.</a>, 210 F.2d 680 (2d Cir. 1954). Adopting the same trade name — letter for letter — is itself evidence of infringement. See <a href="https://www.cetient.com/case/ready-capital-corporation-v-ready-capital-corporation-9747356" target="_blank" rel="noopener">Ready Capital Corporation v. READY CAPITAL CORPORATION</a>, No. 20-CV-00788, 2020 WL 13337953 (S.D.N.Y. May 18, 2020). Such conduct unlawfully appropriates the favorable reputation Plaintiff has built. See <a href="https://www.cetient.com/case/bates-mfg-co-v-bates-numbering-mach-co-9309169" target="_blank" rel="noopener">Bates Mfg. Co. v. Bates Numbering Mach. Co.</a>, 172 F. 892 (3d Cir. 1909).</p>
<p><span class="num">26.</span>Defendant has engaged in this infringing conduct willfully, wantonly, and with conscious disregard for Plaintiff&rsquo;s rights.</p>

<h3>Second Claim for Relief<br/><span style="font-weight:400;">(Federal Unfair Competition in Violation of Section 43(a) of the Lanham Act, 15 U.S.C. &sect; 1125(a))</span></h3>
<p><span class="num">27.</span>Plaintiff incorporates by reference all preceding paragraphs as if fully set forth herein.</p>
<p><span class="num">28.</span>Defendant&rsquo;s actions constitute unfair competition in violation of Section 43(a) of the Lanham Act, 15 U.S.C. &sect; 1125(a).</p>
<p><span class="num">29.</span>By using Plaintiff&rsquo;s exact trade name as a product title, Defendant is engaging in a classic &ldquo;passing off&rdquo; scheme, calculated to deceive consumers into believing that Defendant&rsquo;s goods are associated with, sponsored by, or originate from Plaintiff. This conduct creates a false designation of origin and a false and misleading representation of fact likely to cause confusion. See <a href="https://www.cetient.com/case/borescopes-r-us-v-1800endoscope-com-llc-2477928" target="_blank" rel="noopener">Borescopes R US v. 1800Endoscope.Com, LLC</a>, 728 F. Supp. 2d 938, 951 (M.D. Tenn. 2010). One may not lawfully use a trade name to lead customers to suppose the user&rsquo;s product is the product of another. <a href="https://www.cetient.com/case/weiss-v-the-stork-gift-shop-3581479" target="_blank" rel="noopener">Weiss v. the Stork Gift Shop</a>, 45 A.2d 688 (N.J. Ch. 1946); <a href="https://www.cetient.com/case/51-west-51st-corp-v-roland-3585982" target="_blank" rel="noopener">51 West 51st Corp. v. Roland</a>, 50 A.2d 369 (N.J. Ch. 1946).</p>
<p><span class="num">30.</span>Defendant&rsquo;s conduct has caused and, unless enjoined, will continue to cause irreparable harm to Plaintiff&rsquo;s business, reputation, and goodwill.</p>

<h3>Third Claim for Relief<br/><span style="font-weight:400;">(Cybersquatting in Violation of the Anticybersquatting Consumer Protection Act, 15 U.S.C. &sect; 1125(d))</span></h3>
<p><span class="num">31.</span>Plaintiff incorporates by reference all preceding paragraphs as if fully set forth herein.</p>
<p><span class="num">32.</span>Defendant is in violation of the Anticybersquatting Consumer Protection Act (ACPA), 15 U.S.C. &sect; 1125(d).</p>
<p><span class="num">33.</span>Defendant&rsquo;s conduct meets all four statutory elements for an ACPA violation: (1) Defendant registered, trafficked in, or used a domain name (theroof.store); (2) that domain name is identical or confusingly similar to a mark owned by Plaintiff (THE ROOF STORE); (3) Plaintiff&rsquo;s mark was distinctive at the time of the domain name&rsquo;s registration, having acquired secondary meaning over 27 years of prior use; and (4) Defendant registered the domain name with a bad-faith intent to profit from Plaintiff&rsquo;s mark. See <a href="https://www.cetient.com/case/wagner-v-lindawagnercom-7321643" target="_blank" rel="noopener">Wagner v. lindawagner.com</a>, 202 F. Supp. 3d 574 (E.D. Va. 2016).</p>
<p><span class="num">34.</span>Defendant&rsquo;s bad-faith intent to profit is established by the totality of the circumstances and numerous statutory factors under 15 U.S.C. &sect; 1125(d)(1)(B)(i). See <a href="https://www.cetient.com/case/cable-news-network-lp-lllp-v-cnnewscom-2571196" target="_blank" rel="noopener">Cable News Network L.P., L.L.L.P. v. CNNews.com</a>, 177 F. Supp. 2d 506 (E.D. Va. 2001); <a href="https://www.cetient.com/case/venetian-casino-resort-llc-v-venetiangold-com-2461337" target="_blank" rel="noopener">Venetian Casino Resort, LLC v. Venetiangold.Com</a>, 380 F. Supp. 2d 737 (E.D. Va. 2005).</p>
<p><span class="num">35.</span>Specifically, Defendant&rsquo;s bad faith is demonstrated by:</p>
<p style="margin-left:1.5rem;"><strong>a. Actual Knowledge:</strong> Exhibit S proves Defendant had actual knowledge of Plaintiff&rsquo;s mark and business. Defendant registered the domain name with a bad-faith intent to profit from the famousness of the mark. See <a href="https://www.cetient.com/case/virtual-works-inc-v-network-solutions-2967329" target="_blank" rel="noopener">Virtual Works, Inc. v. Network Solutions</a>, 238 F.3d 264 (4th Cir. 2001).</p>
<p style="margin-left:1.5rem;"><strong>b. Willful Blindness:</strong> Even absent Exhibit S, any basic WHOIS or search engine query at the time of registration would have revealed theroofstore.net and its 20-year digital footprint. Failure to conduct such an elementary search constitutes willful blindness and is evidence of bad faith. See <a href="https://www.cetient.com/case/eurotech-inc-v-cosmos-european-travels-aktiengesellschaft-2361870" target="_blank" rel="noopener">Eurotech, Inc. v. Cosmos European Travels Aktiengesellschaft</a>, 213 F. Supp. 2d 612 (E.D. Va. 2002). The bad-faith analysis applies to subsequent re-registrations or transfers as well. See <a href="https://www.cetient.com/case/xereas-v-heiss-2660868" target="_blank" rel="noopener">Xereas v. Heiss</a>, 933 F. Supp. 2d 1 (D.D.C. 2013).</p>
<p style="margin-left:1.5rem;"><strong>c. Lack of Rights or Legitimate Interest:</strong> Defendant has no trademark or other intellectual property rights in the name and the name is not Defendant&rsquo;s legal name or a name commonly used to identify Defendant.</p>
<p style="margin-left:1.5rem;"><strong>d. Intent to Divert Consumers:</strong> Defendant uses the domain name to create a likelihood of confusion and divert consumers to its own competing commercial website for commercial gain.</p>

<h3>Fourth Claim for Relief<br/><span style="font-weight:400;">(Common Law Trademark Infringement — Florida)</span></h3>
<p><span class="num">36.</span>Plaintiff incorporates by reference all preceding paragraphs as if fully set forth herein.</p>
<p><span class="num">37.</span>Under Florida common law, the analysis for trademark infringement is the same as under the Lanham Act, turning on the likelihood of consumer confusion. See <a href="https://www.cetient.com/case/platinum-dragon-international-inc-v-the-individuals-partnerships-and-9652305" target="_blank" rel="noopener">Platinum Dragon International, Inc. v. The Individuals, Partnerships, and Unincorporated Associations Identified on Schedule A</a>, No. 20-CV-62310, 2021 WL 1165038, at *5 (S.D. Fla. Mar. 26, 2021); <a href="https://www.cetient.com/case/apple-corps-limited-v-the-individuals-partnerships-and-unincorporated-9650777" target="_blank" rel="noopener">Apple Corps Limited v. The Individuals, Partnerships, and Unincorporated Associations Identified on Schedule &ldquo;A&rdquo;</a>, No. 19-CV-24259, 2020 WL 758713, at *3 (S.D. Fla. Feb. 13, 2020); <a href="https://www.cetient.com/case/louis-vuitton-malletier-v-aaalvsalecom-9652648" target="_blank" rel="noopener">Louis Vuitton Malletier v. aaalvsale.com</a>, No. 20-CV-61108, 2021 WL 2210815, at *4 (S.D. Fla. May 28, 2021).</p>
<p><span class="num">38.</span>Plaintiff is the senior user of THE ROOF STORE mark in Florida and holds superior common-law rights. Common-law rights belong to the one who first uses them and gives them value. See <a href="https://www.cetient.com/case/stout-v-laws-3413305" target="_blank" rel="noopener">Stout v. Laws</a>, 37 Haw. 382 (Haw. 1946).</p>
<p><span class="num">39.</span>Defendant&rsquo;s entry into Plaintiff&rsquo;s home market is actionable. The Tea Rose&ndash;Rectanus doctrine does not protect a junior user who invades the established territory of a senior user. Defendant&rsquo;s sales and marketing into South Florida constitute a direct infringement upon Plaintiff&rsquo;s senior rights. See <a href="https://www.cetient.com/case/accu-personnel-inc-v-accustaff-inc-1687300" target="_blank" rel="noopener">ACCU Personnel, Inc. v. AccuStaff, Inc.</a>, 846 F. Supp. 1191 (D. Del. 1994); <a href="https://www.cetient.com/case/smj-j-inc-v-nrg-heat-power-llc-8721356" target="_blank" rel="noopener">SMJ &amp; J, Inc. v. NRG Heat &amp; Power, LLC</a>, 912 F. Supp. 2d 189 (M.D. Pa. 2012); <a href="https://www.cetient.com/case/architemps-inc-v-architemps-ltd-1440294" target="_blank" rel="noopener">Architemps, Inc. v. Architemps, Ltd.</a>, 704 F. Supp. 39 (S.D.N.Y. 1988).</p>
<p><span class="num">40.</span>Defendant&rsquo;s conduct constitutes common law trademark infringement under the laws of the State of Florida.</p>

<h3>Fifth Claim for Relief<br/><span style="font-weight:400;">(Common Law Unfair Competition — Florida)</span></h3>
<p><span class="num">41.</span>Plaintiff incorporates by reference all preceding paragraphs as if fully set forth herein.</p>
<p><span class="num">42.</span>The same facts that support a claim for trademark infringement also support an action for unfair competition under Florida common law, as the legal analysis is identical. See Platinum Dragon, 2021 WL 1165038, at *5.</p>
<p><span class="num">43.</span>Defendant&rsquo;s conduct, including the use of a confusingly similar domain name and the passing off of its product by using Plaintiff&rsquo;s exact trade name, constitutes unfair competition, including palming off, under the common law of the State of Florida.</p>
<p><span class="num">44.</span>Defendant has misappropriated the goodwill and reputation that Plaintiff has developed in its mark through decades of investment and effort.</p>

<h3>Prayer for Relief</h3>
<p>WHEREFORE, Plaintiff respectfully requests that this Court enter judgment against Defendant and grant the following relief:</p>
<ol class="relief">
<li>A permanent injunction enjoining Defendant, and all of its agents, servants, employees, attorneys, and all persons in active concert or participation with Defendant, from using the mark &ldquo;The Roof Store,&rdquo; the domain name theroof.store, or any confusingly similar mark or domain name, in connection with the advertising, offering for sale, sale, or distribution of any goods or services;</li>
<li>An order directing Defendant to transfer the domain name theroof.store to Plaintiff;</li>
<li>An order requiring Defendant to cease using &ldquo;The Roof Store&rdquo; in any product title, packaging, advertising, or promotional materials;</li>
<li>An award of Plaintiff&rsquo;s actual damages in an amount to be proven at trial;</li>
<li>Alternatively, an award of statutory damages under 15 U.S.C. &sect; 1117(d) for Defendant&rsquo;s violation of the ACPA in an amount of not less than $1,000 and not more than $100,000 per domain name, as the Court deems just;</li>
<li>An order requiring Defendant to account for and disgorge all profits resulting from the infringing conduct;</li>
<li>An award of damages for injury to Plaintiff&rsquo;s goodwill and reputation;</li>
<li>An award of enhanced damages and/or treble damages for willful infringement;</li>
<li>An award of pre- and post-judgment interest;</li>
<li>An award of Plaintiff&rsquo;s costs and reasonable attorney&rsquo;s fees pursuant to 15 U.S.C. &sect; 1117, as this is an exceptional case;</li>
<li>Such other and further relief as the Court may deem just and proper.</li>
</ol>

<h3>Jury Demand</h3>
<p>Plaintiff hereby demands a jury trial on all issues so triable.</p>

<p style="margin-top:2rem;">Dated: August 2, 2026</p>
<p>Respectfully submitted,</p>
<p><span class="fill">[Counsel signature block — to be completed]</span><br/>Attorneys for Plaintiff The Roof Store</p>
</div>
`;
